//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyLotteryBot.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participants
    {
        public int ParticipantId { get; set; }
        public int LotteryId { get; set; }
        public int ProfileId { get; set; }
        public int Value { get; set; }
        public bool IsWinner { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
    
        public virtual Lottery Lotteries { get; set; }
        public virtual Profile Profiles { get; set; }
    }
}
